[build]
  command = "pip install --upgrade pip && pip install -r requirements.txt && pip install -r netlify/functions/server/requirements.txt"
  publish = "public"
  functions = "netlify/functions"

[dev]
  command = "python gui_web.py"
  targetPort = 5000
  publish = "public"
  autoLaunch = true

[build.environment]
  PYTHON_VERSION = "3.9"
  FLASK_APP = "gui_web:app"
  FLASK_ENV = "production"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/server/:splat"
  status = 200
  force = false

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  directory = "netlify/functions"

# Python version configuration for Netlify
[context.production.environment]
  PYTHON_VERSION = "3.9"

[context.deploy-preview.environment]
  PYTHON_VERSION = "3.9"

[context.branch-deploy.environment]
  PYTHON_VERSION = "3.9"
